name: Crear Pochi OS APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Preparar Android
        uses: android-actions/setup-android@v3

      - name: Ver archivos
        run: ls -la
